var pathCalendar = "DC_RCalendar";
var pathServer = 'http://www.mrsite.co.uk';
document.write('<link rel="stylesheet" type="text/css" href="css/bookingtool/bookingtool.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/fonts-min.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/button.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/container.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/calendar.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/DCEventCalendar.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/editor.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/tabview.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/jquery.tooltip.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/jquery.contextMenu.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/tablesorter/style.css" />');
document.write('<link rel="stylesheet" type="text/css" href="css/UI/jquery-ui-1.7.3.custom.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/template.css" />');
document.write('<link rel="stylesheet" type="text/css" href="'+pathCalendar+'/css/validationEngine.jquery.css" />');

document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/utilities.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/yahoo.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/dom.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/calendar.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/button.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/container.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/event.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/element.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/calendarcolors.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.blockUI.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.contextMenu.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.tablesorter.min.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.cookies.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/JSON.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.validationEngine.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.validationEngine-en.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery-ui-1.7.2.custom.min.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/jquery.tooltip.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/dateformat.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/DCEventCalendarHotelBooking.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/intervalcalendar.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/DCEventCalendarRequesters.js"></scr'+'ipt>');
document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+pathCalendar+'/printArea.js"></scr'+'ipt>');

